DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS watchlists CASCADE;
DROP TABLE IF EXISTS watchlists_games CASCADE; 

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR (255) NOT NULL,
  last_name VARCHAR (255) NOT NULL,
  email VARCHAR (255) UNIQUE NOT NULL,
  u_id VARCHAR (255) UNIQUE NOT NULL
);

CREATE TABLE games (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR (255) NOT NULL,
  category VARCHAR (255),
  rating_number DECIMAL,
  rating_word VARCHAR (255)
);

CREATE TABLE watchlists (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR (255) NOT NULL
);

CREATE TABLE watchlists_games (
  id SERIAL PRIMARY KEY NOT NULL,
  watchlist_id INTEGER REFERENCES watchlists(id) ON DELETE CASCADE,
  game_id INTEGER REFERENCES games(id) ON DELETE CASCADE
);